#roadnottaken
base: &base
  adapter: mysql2
  host: localhost
  username: root
  password: 

development:
  <<: *base
  database: roadnottaken

test:
  <<: *base
  database: roadnottaken_test

qa:
  <<: *base
  database: roadnottaken_qa

production:
  <<: *base
  database: roadnottaken_production

